// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StoreDataAccessLayer;

#nullable disable

namespace StoreDataLayer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250120000000_AddGuestColumnsToOrders")]
    partial class AddGuestColumnsToOrders
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // This is a partial migration, the model will be updated by the next full migration
        }
    }
}

